spring:
  application:
    name: electronic-store
  datasource:
    url: jdbc:postgresql://interchange.proxy.rlwy.net:45516/railway
    username: postgres
    password: hgVqNVoCnUfEROjIAlzOhugeXMLvIwIU
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

file:
  upload-dir: D:/Spring Boot/upload

cloudinary:
  cloud-name: dciecegu7
  api-key: 293575831448855
  api-secret: ip3ygQlgRT5QYb-ERpSkXoSOywA